version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rewards
      - DB_PORT=5432
      - JWT_SECRET_KEY=supersecretkey
    depends_on:
      - db
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./migrations:/app/migrations
    networks:
      default:
        ipv4_address: 172.30.0.2

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rewards
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.30.0.3

volumes:
  postgres_data:


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
